# Generated by Django 4.0.3 on 2022-04-04 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99999)),
                ('chain_id', models.CharField(max_length=99999)),
            ],
            options={
                'db_table': 'chain',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99999)),
                ('url', models.CharField(max_length=99999)),
                ('symbol', models.CharField(max_length=99999)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='latency.chain')),
            ],
            options={
                'db_table': 'provider',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('p25', models.FloatField()),
                ('p50', models.FloatField()),
                ('p75', models.FloatField()),
                ('p90', models.FloatField()),
                ('p99', models.FloatField()),
                ('mean', models.FloatField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='latency.provider')),
            ],
            options={
                'db_table': 'benchmark',
                'managed': True,
            },
        ),
    ]
